// Generated by CoffeeScript 1.4.0
(function() {
  var Boleto, DIA_0, DIA_EM_MS, MASCARA_DIAS, MASCARA_PRECO, NUMERO_RE, ctx;

  DIA_EM_MS = 1000 * 60 * 60 * 24;

  DIA_0 = new Date(Date.UTC(1997, 9, 7));

  MASCARA_PRECO = "0000000000";

  MASCARA_DIAS = "0000";

  NUMERO_RE = /^(\d{3})(\d)(\d{5})(\d)(\d{5})(\d{5})(\d)(\d{10})(\d)(\d)(\d{4})(\d{10})$/;

  ctx = typeof exports !== "undefined" && exports !== null ? exports : this;

  Boleto = (function() {

    function Boleto(num) {
      var $;
      this.num = num;
      $ = num.match(NUMERO_RE);
      if (!$) {
        throw new Error("Número de boleto inválido");
      }
      this.banco = $[1];
      this.moeda = $[2];
      this.vencimento = $[11];
      this.preco = $[12];
      this.nosso_numero = $[3] + $[5];
      this.favorecido = $[6] + $[8];
      this.digito1 = $[4];
      this.digito2 = $[7];
      this.digito3 = $[9];
      this.digito_geral = $[10];
    }

    Boleto.prototype.getVencimentoComoData = function() {
      return this.getDiasComoData(parseInt(this.vencimento));
    };

    Boleto.prototype.getDiasComoData = function(dias) {
      return new Date(DIA_0.getTime() + dias * DIA_EM_MS);
    };

    Boleto.prototype.getDateComoDias = function(dt) {
      return (dt.getTime() - DIA_0.getTime()) / DIA_EM_MS;
    };

    Boleto.prototype.formatarPreco = function(p) {
      p = p.replace(/,|\./g, '');
      return MASCARA_PRECO.substring(p.length) + p;
    };

    Boleto.prototype.alterarVencimento = function(dt) {
      var dias;
      if (dt.getUTCHours()) {
        throw Error("Data deve ser uma data em UTC");
      }
      if (dt.getTime() < DIA_0.getTime()) {
        throw Error("Data inválida");
      }
      dias = '' + this.getDateComoDias(dt);
      this.vencimento = MASCARA_DIAS.substring(dias.length) + dias;
      return this.atualizarDigitoGeral();
    };

    Boleto.prototype.alterarValor = function(vl) {
      this.preco = this.formatarPreco(vl);
      return this.atualizarDigitoGeral();
    };

    Boleto.prototype.atualizarDigitoGeral = function() {
      return this.digito_geral = this.__calcularDigitoGeral();
    };

    Boleto.prototype.getNumeroFormatado = function() {
      return ("" + this.banco + this.moeda + this.nosso_numero[0] + "." + this.nosso_numero.slice(1, 5) + this.digito1 + " ") + ("" + this.nosso_numero.slice(5) + "." + this.favorecido.slice(0, 5) + this.digito2 + " ") + ("" + this.favorecido.slice(5, 10) + "." + this.favorecido.slice(10, 15) + this.digito3 + " ") + ("" + this.digito_geral + " ") + ("" + this.vencimento + this.preco);
    };

    Boleto.prototype.__calcularDigitoGeral = function() {
      var reg, sum;
      reg = this.banco + this.moeda + this.vencimento + this.preco + this.nosso_numero + this.favorecido;
      sum = reg.split('').reverse().reduce(function(p, c, i) {
        c = parseInt(c);
        return p + (i % 8 + 2) * c;
      }, 0);
      sum = 11 - (sum % 11);
      if (sum > 9) {
        sum = 1;
      }
      return sum;
    };

    return Boleto;

  })();

  ctx.Boleto = Boleto;

}).call(this);
